[package]
name = "lavan"
version = "0.0.3-a-unstable"
authors = ["Sabi <sabitheotome@gmail.com>"]
description = "Lavan is a parser library"
license = "GPL-3.0"
repository = "https://github.com/sabitheotome/lavan"
edition = "2021"

[dependencies]
either = { version = "1.9.0", optional = true }

[features]
default = ["either"]
either = ["dep:either"]
experimental = []
